### ISSUE TITLE
MiniKeePass for iOS still owes you some major changes from users

### ISSUE THREAD

**Issue by jfpalaciosbalbas** [MiniKeePass/MiniKeePass#540] opened 2017-10-01 01:00 UTC
Neither in this current or previous versions have been able to view attachments and sync with applications in the Dropbox, OneDrive o Google Drive or any.

**Comment by azusabush-1** [comment] 2017-10-01 04:08
I confirm the problem. On iPhone7 with the update for iOs11 there is no possibility to synchronize via Dropbox

**Comment by jarush** [comment] 2017-10-03 01:26
Duplicate of existing issues.  Closing

**Closed by jarush** 2017-10-03 01:26 UTC
