### ISSUE TITLE
Missing Search field

### ISSUE THREAD

**Issue by pcoggins** [MiniKeePass/MiniKeePass#535] opened 2017-09-29 17:23 UTC
Missing search field introduced in v1.7 for iOS. please add back into next release. seach functionality is crucial

**Comment by jarush** [comment] 2017-09-29 17:24
Duplicate of #509. An update to restore search functionality is in the app store review process.

**Comment by szanon** [comment] 2017-09-30 06:00
Please add search functionality back. This is one of the most crucial functions.

**Comment by RainbowRisingForce** [comment] 2017-09-30 10:32
Please, I have the same issue. Search filed is very helpful, could you add again on next release?

**Comment by drc12301** [comment] 2017-09-30 10:40
Please add search functionality back. I use it frequently.

**Comment by peet21** [comment] 2017-09-30 11:12
without search-function, minikeepass is worthless

**Closed** 2017-09-30 12:44 UTC
