### ISSUE TITLE
Search feature needs to be added back!

### ISSUE THREAD

**Issue by djwasser** [MiniKeePass/MiniKeePass#523] opened 2017-09-28 16:50 UTC
The latest update (v1.7) for iOS removed search feature.  The app is essentially worthless without search as it is no longer useable because it is impossible to quickly find password.  Manually tapping through all of them categories is not practical when one has over 1,000 entries.

**Comment by degie** [comment] 2017-09-28 16:57
I need this too! +1

**Comment by ajnsn** [comment] 2017-09-28 17:24
+1

**Comment by Bahramkhandan** [comment] 2017-09-28 17:33
my IOS just updated to version 1.7. I thought it was my font setting or something, but I guess there is a problem with the update. I can not search! need please .

thank you

**Comment by hspinweb** [comment] 2017-09-28 17:53
Agree. Search is essential. I may need to move to another product with out the search

**Comment by Silun** [comment] 2017-09-28 17:57
I second this. Without the search, this app is virtually useless to me. Please add it back.

**Comment by jarush** [comment] 2017-09-28 17:58
Duplicate of issue #509, please use that issue to track progress. A fix has already been submitted to the AppStore for review.

**Closed by jarush** 2017-09-28 17:58 UTC

**Comment by degie** [comment] 2017-09-28 18:02
@jarush I also see the x button disappeared on title input when adding an entry, which delete "New entry" text, this is feature or bug?

**Comment by jarush** [comment] 2017-09-28 21:27
@degie that’s sounds like a bug.
