### ISSUE TITLE
Crashing on IOS 10 & 11

### ISSUE THREAD

**Issue by TitanicRed** [MiniKeePass/MiniKeePass#537] opened 2017-09-30 12:42 UTC
Long time user of Keepass, latest version crashes after entering password on 4 different devices, 3 x IOS 11, 1 x IOS 10.
Seems to be since recent updates.

**Comment by mpetr** [comment] 2017-09-30 16:21
I have touchID and mine keepass crashes just when opening the database (so I got in, but cannot open the database.). I have 3 databases imported, only one (the biggest one) crashes. IOS10, latest minikeepass

**Comment by gabox7** [comment] 2017-09-30 18:34
Same problem With iOS 10.3.3 6s+ ver 1.7.1 please workaround TIA

**Comment by Erreu** [comment] 2017-10-02 02:51
My workaround is to enter titles for all the entries. 

Using IOS 10.3.3 MiniKeePass 1.7.1 I was experiencing the same trouble when I opened folder that contained entries without Titles (blank Titles). When I used a different a different device to edit the database and enter a title for each entry the folders open normally. I also had to ensure there were no blank Titles for entries in main (default) folder.

**Comment by mpetr** [comment] 2017-10-02 09:47
thanks @Erreu 
Workaround working for me.

**Comment by postmoik** [comment] 2017-10-02 19:06
thanks @Erreu . This works for me too.

**Comment by jarush** [comment] 2017-10-03 01:27
I think this is a duplicate of #526. We will try and get 1.7.2 in the app store soon, and if that doesn't fix it please open a new issue.

**Closed by jarush** 2017-10-03 01:27 UTC
