### ISSUE TITLE
Updated 1.7 - now no search feature 

### ISSUE THREAD

**Issue by webbasedmoney** [MiniKeePass/MiniKeePass#529] opened 2017-09-29 02:59 UTC
IPhone 6s Plus 
Version 10.2.1

Updated 1.7 MiniKeePass September 27 

Now have no search feature !!

**Comment by jarush** [comment] 2017-09-29 03:10
Duplicate of issue #509, please use that issue to track progress. A fix has already been submitted to the AppStore for review.

**Closed by jarush** 2017-09-29 03:10 UTC
