### ISSUE TITLE
Search is gone

### ISSUE THREAD

**Issue by HuweyII** [MiniKeePass/MiniKeePass#512] opened 2017-09-28 00:13 UTC
As of version 1.7 the search bar is missing in the app.  I’m looking at a KDB v1 file I think. If that helps. On an iPhone 8 on iOS 11.

**Comment by shad0whawk** [comment] 2017-09-28 01:21
It’s nice to see an update for this app. I’ve noticed this too in an 8 Plus with iOS 11.01. Very useful feature so it’s be nice to get it back.

**Comment by ninobb** [comment] 2017-09-28 03:37
Yes same for me. Search is gone. Significant problem for me as I have 100s of accounts. Also on iOS 11.0.1 and iPhone 8 plus.

**Comment by kriegaex** [comment] 2017-09-28 03:39
After more than three years the annoying bug that capital and lower case letters were not recorded correctly when entering my passphrase in order to unlock on my iPad, has finally been fixed. Now I cannot search anymore, and I have tons of passwords. Do you guys test your stuff at all or listen to users? Sorry for being frustrated.

**Comment by Laufnacht** [comment] 2017-09-28 03:47
Also. No Search. iOS 11.1beta1.

Restart of app and device was not successful.

**Comment by daCaPo** [comment] 2017-09-28 04:28
Same here. iOS 11.0.1 on iPhone 5s

**Comment by Ereglam** [comment] 2017-09-28 05:08
Would be really nice if the search field was restored. Can't see any reason why it was removed. 
Now it's a pain trying to find anything quickly.

**Comment by dmgm** [comment] 2017-09-28 05:59
Search missing on iPhone 6, latest iOS and mini hub app. I wonder if search didn’t disappear after the last iOS upgrade.

**Comment by kriegaex** [comment] 2017-09-28 06:22
No, it has to do nothing with iOS upgrade. As I said above, it also happens on iOS 10.3.3, for my device there will be no iOS 11 available.

**Comment by alexey3f** [comment] 2017-09-28 06:51
Same here. iOS 10.3.3 on iPhone 6 - Search missing.

**Comment by nakedpony** [comment] 2017-09-28 07:08
+1

**Comment by ltdeta** [comment] 2017-09-28 10:00
+1

**Comment by AndyMilano** [comment] 2017-09-28 10:03
Search is gone as well today when I updated to MiniKeePass 1.7 on my iPhone 6 with iOS 10.3.3

**Comment by jarush** [comment] 2017-09-28 12:43
Duplicate of issue #509, please use that issue to track progress.

**Closed by jarush** 2017-09-28 12:43 UTC
