### ISSUE TITLE
App closes if folder has entries recorded

### ISSUE THREAD

**Issue by rrremedio** [MiniKeePass/MiniKeePass#544] opened 2017-10-01 11:59 UTC
Version 1.7.1 closes after try open folder containing passwords. So, the app becomes useless.

**Comment by Erreu** [comment] 2017-10-02 02:26
I am seeing this same issue on IOS 10.3.3 if the folder contains entries with blank (empty) Title fields. If I use a different device to enter a title for each entry in the folder then it opens normally.

**Comment by jarush** [comment] 2017-10-03 01:25
I think this is a duplicate of #526. We will try and get 1.7.2 in the app store soon, and if that doesn't fix it please open a new issue.

**Closed by jarush** 2017-10-03 01:25 UTC
