### ISSUE TITLE
Can’t search as of version 1.7

### ISSUE THREAD

**Issue by ShaneSparkyYYZ** [MiniKeePass/MiniKeePass#528] opened 2017-09-28 22:06 UTC
Upon opening the app I cannot search at all inside the app as of version 1.7

**Comment by jarush** [comment] 2017-09-28 22:40
Duplicate of issue #509, please use that issue to track progress. A fix has already been submitted to the AppStore for review.

**Closed by jarush** 2017-09-28 22:40 UTC

**Comment by ShaneSparkyYYZ** [comment] 2017-09-30 07:09
Thanks! Sorry I’m new to github, should’ve searched my bad.
