### ISSUE TITLE
Version 1.7, no search available

### ISSUE THREAD

**Issue by olieske** [MiniKeePass/MiniKeePass#534] opened 2017-09-29 11:36 UTC
iOS 11 on iPhone 7
With the new 1.7 Version there 's no search field anymore.

**Comment by jarush** [comment] 2017-09-29 12:22
Duplicate of #509. An update to restore search functionality is in the app store review process.

**Comment by bachrempp** [comment] 2017-09-29 12:22
I have the same issue, what happened the the search box?  Without the ability to search I am lost.

**Closed by jarush** 2017-09-29 12:22 UTC
