### ISSUE TITLE
Unable to search

### ISSUE THREAD

**Issue by msinklair** [MiniKeePass/MiniKeePass#524] opened 2017-09-28 18:27 UTC
In previous versions I was able to slide the password group list down and search.  I am unable to do so with this release (Version 1.7) on my iPhone.  Was this intentional?

**Comment by gitbls** [comment] 2017-09-28 18:49
For completeness I'll mention that the search is gone completely, both at the top of an opened kdbx file, and also within a group. Hoping this was just an "oops".

**Comment by HauserM2407** [comment] 2017-09-28 19:12
Horror, worst case! I don't find my Passwords and more... this has to be fixed soon!

**Comment by flodoardo** [comment] 2017-09-28 19:42
I am storing 200+ passwords organized in different folders. Without search capabilities this application is going to be useless! Why did you remove the in-app-search?

**Comment by Nathank60** [comment] 2017-09-28 19:43
Yes, this is no good. App not usable without search. I hope this is a mistake and you will put it back ASAP.

**Comment by miztahsparklez** [comment] 2017-09-28 20:33
Yup, this is broken as of the latest update!

**Comment by neatgz** [comment] 2017-09-28 21:00
same problem，cannot search with this release (Version 1.7)
this is really a bad news， I am storing 300+ passwords organized in different folders. Without search capabilities this application is going to be hard to use
plz put it back ASAP

**Comment by jarush** [comment] 2017-09-28 21:27
Duplicate of issue #509, please use that issue to track progress. A fix has already been submitted to the AppStore for review.

**Closed by jarush** 2017-09-28 21:27 UTC
