### ISSUE TITLE
Can access app without Touch ID (iOS)

### ISSUE THREAD

**Issue by eicoolguy6** [MiniKeePass/MiniKeePass#414] opened 2015-12-11 19:30 UTC
When prompted for your fingerprint, if you press the home button it bypasses it without the need for a fingerprint.

**Comment by dsteinkopf** [comment] 2015-12-12 08:48
I can confirm this problem :(

**Comment by joshsnelling** [comment] 2016-03-20 23:42
Assuming this dumps you to the password entry screen (as it did for me when I tried it), this is standard behavior for Touch ID enabled apps. Pressing the home button is the same as pressing the cancel button on the Touch ID prompt.

**Comment by obertroll** [comment] 2016-03-27 08:14
I can confirm this issue as I came across it yesterday. This was on iPhone 6S with IOS 9.3.  Disabled TouchID in the app for now as it is quite a bad flaw.

**Comment by obertroll** [comment] 2016-03-27 08:15
Ps: it dumps you at database and allows you to view passwords.

**Comment by joshsnelling** [comment] 2016-03-27 16:07
Okay, then is this a duplicate of issue #406?

**Comment by obertroll** [comment] 2016-03-27 16:10
Hi Josh,
It would appear to be same issue as in 406.
CheersUwe
Sent from Outlook on iOS

    _____________________________

**Comment by joshsnelling** [comment] 2016-03-27 16:27
Thanks for the confirmation, Uwe. I've submitted PR #429 as a proposed fix for this. I hope someone in the project can check this out soon.

**Comment by jarush** [comment] 2016-04-27 13:55
Duplicate #406

**Closed by jarush** 2016-04-27 13:55 UTC
