### ISSUE TITLE
crash on ios11.1 beta opening certain folders

### ISSUE THREAD

**Issue by bendingunit** [MiniKeePass/MiniKeePass#536] opened 2017-09-30 11:34 UTC
I know it's just an iOS-beta (build 15b5066f), but might still be interesting for the developers. I'm using the latest version available of MiniKeePass (1.7). Opening my database using TouchID works fine, trying to open several of my folders leads to a crash of the application - some folders and the entries within them can be opened without any problems, though.

**Comment by Erreu** [comment] 2017-10-02 02:59
It might be related to an entry with a blank title? https://github.com/MiniKeePass/MiniKeePass/issues/537#issuecomment-333430017

**Comment by jarush** [comment] 2017-10-03 01:28
I think this is a duplicate of #526. We will try and get 1.7.2 in the app store soon, and if that doesn't fix it please open a new issue.

**Closed by jarush** 2017-10-03 01:28 UTC
