### ISSUE TITLE
HELP please reinstall the search field. 

### ISSUE THREAD

**Issue by shopsuppers** [MiniKeePass/MiniKeePass#517] opened 2017-09-28 07:57 UTC

**Comment by tyronedougherty** [comment] 2017-09-28 12:36
+1 The search field was very useful! Now that it's gone it takes considerably more time to locate my passwords

**Comment by jarush** [comment] 2017-09-28 12:43
Duplicate of issue #509, please use that issue to track progress.

**Closed by jarush** 2017-09-28 12:43 UTC
